### ISSUE TITLE
2024/7/24(水) 議事録

### ISSUE THREAD

**Issue by tsukimi0618** [RyosukeSakakibara718/project-balancer_doc#12]
# 日時
2024/7/24(水) 18:45-20:15

# 参加者(敬称略)
榊原、山崎、横浜、奈良

# アジェンダ
スプリントの振り返り
次のスプリントの設定
要件定義

# スプリントの振り返り＆次のスプリントの設定

**予想と実際の工数どうだった？**
->バッファを取ったから余裕を持って終えた。
RVも込みでの工数だと期限が曖昧になっている。
 
**対策**
最初の４日で作成、残りの３日でRV->修正
 
 
**vercel構築**
イテレーション2からは抜く
 

**PHP stan設定**
イテレーション2に設定
検証方法を調べた上で、gitのコミットのタイミングで、動かせるように設定したい
 

**ディレクトリ構成**
Atomicデザインとbullet-proofの良いところまとめた。
 

> * atoms : ボタンやテキストフィールドなどの最小単位のパーツ
>     * pages配下には置かない
> * molecules : ロジックを含まないコンポーネント
>     * ここで指すロジックとは、条件によって表示を変更する処理
> * organisms : ロジックを含むコンポーネント
>     * ここで指すロジックとは、条件によって表示を変更する処理
> * templates : moleculesとorganismsのみが記載されているコンポーネント

 

**moleculesに書いたものをorganismsで呼び出さない認識でよいか？**
->認識相違なし。 templatesにはロジックを書いてもよい。
 
**テストケースはどうする？**
->カバレッジを設定することにする。
方針として、フロントを95%
テスト駆動開発（以下、TDD）はバックエンドのみ
 
**componentsテストは必要？**
-> templatesを作成した場合のみ必要
グローバルのtemplatesに限り、他のtemplates共存可能とする
 

**コーディング規約（フロントエンド）について**
特段の問題なし
**TODO**

- [x] 型に関しての記載
- [x] importの順序の記載

 
 
**コーディング規約（バックエンド）について**
特段の問題なし
モデル作成時のルールをどうする？
->必要に応じてモデル作成時にオプション付け足して適宜コントローラーを作成する。
 
 
**ディレクトリ構成（バックエンド）について**
特段の問題なし
 

**PHP pintについて**
特段の問題なし
 
 
**DB作成 supabase**
特段の問題なし
 
 
**Prettier,ESlint環境構築**
特段の問題なし
 
 
**vitest設定**
特段の問題なし
 

**PHP unit**
特段の問題なし
 
 
**CI/CD構築**
まだ先の話だからイテレーションからはずす。

# 総括
イテレーション１は、工数にRVを含めるかなどのすり合わせが甘かった。
イテレーション２は、最初の４日で作成、残りの３日でRV->修正

# 要件定義
ワイヤーフレームを５画面作成
DB設定など

**Comment by RyosukeSakakibara718** [comment]
@tsukimi0618 

ありがとうございます！
内容完璧です！

ToDo助かりました^ ^
