### ISSUE TITLE
DB設計

### ISSUE THREAD

**Issue by RyosukeSakakibara718** [RyosukeSakakibara718/project-balancer_doc#14]
![Image](https://github.com/user-attachments/assets/85b03010-039e-4da3-9fb0-8ba95746ce37)

**Comment by RyosukeSakakibara718** [comment]
@yokohama-TN 

少しSSOに関して調べましたが、[Laravel Socialite](https://readouble.com/laravel/8.x/ja/socialite.html)でいけるかなと思います。
Laravel Socialite を使うのであれば、自前でテーブルを用意する必要はなさそうでした！

**Comment by RyosukeSakakibara718** [comment]
https://www.figma.com/design/nVVtG6m7amRrLpqIQMu5MX/project-balancer?node-id=37-62689&t=36hLgpfds23nDQd1-0

こちらで確認できます！

**Comment by tsukimi0618** [comment]
ER図のリレーションシップ（一対多）などを表現してください！
参考：https://www.ntt.com/business/sdpf/knowledge/archive_50.html

**Comment by yokohama-TN** [comment]
@RyosukeSakakibara718 
- [x] commentsテーブルのcommentカラムはvarchara(255)じゃ足りない気がします！
text型の方が良いでしょう！
最大文字数は改めて検討して、バックエンド側のバリデーションで処理しましょう！
->varchar(1000)で対応します！

- [x] membersテーブルにメンバーごとの予定総工数を持つカラムが欲しいです！
ホームのメンバー情報の予定工数を表示するため。
->assignment_membersテーブルに記載

- [x] ~~membersテーブルとprojectsテーブルがつながっているはずなのにER図上は繋がっていない。~~

- [x] membersテーブルにnameカラムがないよw

- [x] membersテーブルのpostionカラムは案件によって変わるので、membersテーブルで固定で管理できない。というかmembersテーブルとprojectテーブルを直接繋ぐと不都合ありそう。中間テーブルを用意して、プロジェクトごとにメンバーが登録される形にしようか。membersテーブルからproject_idカラムは削除で。
この説明だけだとわからないかもしれないので、15時以降に分からなかったら直接話しましょ！連絡ください！

- [x] membersテーブルとusersテーブルを繋ぐ必要はないです。usersテーブルはログインと権限管理のためだけに使うので独立していて問題ありません。



## メンバーの月毎の予定工数はどうやって登録しようか検討必要そう！

**Comment by yokohama-TN** [comment]
approve

**Comment by RyosukeSakakibara718** [comment]
fix
