### ISSUE TITLE
ワイヤーフレーム - ホーム画面(請負収支報告)

### ISSUE THREAD

**Issue by yokohama-TN** [RyosukeSakakibara718/project-balancer_doc#15]
ホーム画面WF作成
https://www.figma.com/design/nVVtG6m7amRrLpqIQMu5MX/project-balancer?node-id=3-40&t=BnKwYxRAGUv6IOwJ-0

気にある点あればこちらのコメントまで
問題なければGoodで！

**Comment by RyosukeSakakibara718** [comment]
@yokohama-TN 

ホーム画面からコメントの新規作成でモーダルなのか、新しいフォームが差し込まれるかされるかと思うのですが、
そのWFは今回は作成しない方針でしょうか？
その他は問題ないかと思いました！

**Comment by yokohama-TN** [comment]
@RyosukeSakakibara718 
考慮漏れでした！
新しいフォームが差し込まれて、ボタンで送信、キャンセルを選択するようにUI変えました！

**Comment by yokohama-TN** [comment]
コメントの削除機能要検討

**Comment by RyosukeSakakibara718** [comment]
反映ありがとうございます！
その他は問題ないです！

**Comment by yokohama-TN** [comment]
コメントに削除ボタン配置
