### ISSUE TITLE
ワイヤーフレーム - ログイン

### ISSUE THREAD

**Issue by tsukimi0618** [RyosukeSakakibara718/project-balancer_doc#18]
ログイン画面WF作成
https://www.figma.com/design/nVVtG6m7amRrLpqIQMu5MX/project-balancer?node-id=35-75&t=Z1qUrNWWdaCoAqoh-1

気にある点あればこちらのコメントまで
問題なければGoodで！

**Comment by RyosukeSakakibara718** [comment]
いいと思います！

**Comment by yokohama-TN** [comment]
@tsukimi0618 
actual costの記入をお願いします

**Comment by tsukimi0618** [comment]
@yokohama-TN 
ログイン画面にですか・・・？

**Comment by yokohama-TN** [comment]
@tsukimi0618 
figmaの話じゃないです！
issueのprojectsにです！
実際の作業時間を入れて欲しいということです

**Comment by tsukimi0618** [comment]
いれました！
