### ISSUE TITLE
ワイヤーフレーム - ユーザー管理マスタ

### ISSUE THREAD

**Issue by tsukimi0618** [RyosukeSakakibara718/project-balancer_doc#19]
ユーザー管理画面WF作成
https://www.figma.com/design/nVVtG6m7amRrLpqIQMu5MX/project-balancer?node-id=3-43&t=Z1qUrNWWdaCoAqoh-1

気にある点あればこちらのコメントまで
問題なければGoodで！

**Comment by RyosukeSakakibara718** [comment]
@tsukimi0618 

これってユーザー追加機能とかは必要ないですかね？

**Comment by yokohama-TN** [comment]
@RyosukeSakakibara718 
ユーザーはスクラムポイントと一緒でログインすることによって作成されます。
