### ISSUE TITLE
ワイヤーフレーム - メンバー管理マスタ

### ISSUE THREAD

**Issue by RyosukeSakakibara718** [RyosukeSakakibara718/project-balancer_doc#20]

**Comment by tsukimi0618** [comment]
メンバー管理画面訂正しました。
コメントにあった等級と開始日を追加しました。
終了日もコメントでは必要とありましたが、これってmemberテーブルに合わせるなら終了日必要ないと思うのですがいかかでしょうか？
projectsテーブルにはend_dateまだあるけど、結局どうなんだっけ？
https://www.figma.com/design/nVVtG6m7amRrLpqIQMu5MX/project-balancer?node-id=3-42&t=IHHdExluWtWFo8xX-1
