### ISSUE TITLE
ワイヤーフレーム - 案件管理画面

### ISSUE THREAD

**Issue by RyosukeSakakibara718** [RyosukeSakakibara718/project-balancer_doc#21]

**Comment by tsukimi0618** [comment]
モーダルを追加しました。
お手隙の際にRVお願いします。
https://www.figma.com/design/nVVtG6m7amRrLpqIQMu5MX/project-balancer?node-id=3-41&t=Xabp6q4y2yijCgxy-1

**Comment by RyosukeSakakibara718** [comment]
@tsukimi0618 

作業ありがとうございます！
figmaのコメントを2件追加いたしました！
