### ISSUE TITLE
【2024/08/07】議事録

### ISSUE THREAD

**Issue by yokohama-TN** [RyosukeSakakibara718/project-balancer_doc#27]
### globalStateの是非
- APIを叩くタイミングでコントロール
- 学習コストを考慮すると難しい
- グローバル管理、バケツリレーはどうする？
- propsのアンチパターンをさがすのにもprops管理したい
=> useContextを使う

### ボタンのレイアウトはpropsでコントロールするのか？
- 一つ作ってコントロールする
- Atomsにそんなにロジック書いて良いの？
=>Atoms内でも引数で分ける

### 最初のRVは膨大になる
- まずはモックで作ってみたら？
- パーツごとにタスクを分けても良い？
=> タスクを分ける

### どの単位でタスクを分けるか
=> 榊原がタスクを振る

### ユニットテストむずい
- 今回はテスト駆動風

### なぜおわらなかったのか？
- 作業フローが定まってなかった

### 小タスクを作る
- 最初にPRを作る方法ある
=>横浜一旦タスク切る

## 山崎
- シーケンス図解説 #25

**Comment by tsukimi0618** [comment]
確認しました！ありがとうございます！問題ないです！

**Comment by RyosukeSakakibara718** [comment]
確認しました。

内容として記載すべきかどうか、ここは見分ける必要があります。
またお話ししましょう

今回は一旦OKとします。
