### ISSUE TITLE
【2024/08/29】議事録

### ISSUE THREAD

**Issue by tsukimi0618** [RyosukeSakakibara718/project-balancer_doc#36]
議事録 18:30 ~ 20:00 定例 進捗報告

議事録の粒度細かく書いたけど消えちゃったので内容完結にまとめる

# 振り返り
メンバー管理画面 / フロント実装 #22 
マージ済み（エラーや考慮漏れあったら都度修正）

エイリアスを設定して絶対パスでインポートするように修正[#84](https://github.com/RyosukeSakakibara718/project-balancer/issues/84) 
赤線でるからマージできていない要調査

[doc: 案件管理画面要件書作成 #35](https://github.com/RyosukeSakakibara718/project-balancer_doc/pull/35/commits/5810898d2950c6da7d4298f9b02a669abefc098b?short_path=38677ac)の説明

総括：みんな実装をほとんど終えていた

# 反省
特定のタスクを終えないと、他に進められないタスクの切り方や振り方は考慮すべき

# [ iteration 7でのタスク（TODO含む）](https://github.com/users/RyosukeSakakibara718/projects/4/views/1?sliceBy%5BcolumnId%5D=120935600&sliceBy%5Bvalue%5D=Iteration+7)

## 榊原
案件管理画面/デザイン作成
[#122](https://github.com/RyosukeSakakibara718/project-balancer/issues/122)  

## 横浜
案件管理画面/シーケンス図作成
[#33](https://github.com/RyosukeSakakibara718/project-balancer_doc/issues/33)

下記画面のソート機能の削除・ソートボタンを作成
<img width="724" alt="スクリーンショット 2024-08-29 19 24 22" src="https://github.com/user-attachments/assets/3718d364-0454-4241-95e4-7dc5154b2342">

エラーレスポンス404・403の記述を削除
<img width="772" alt="スクリーンショット 2024-08-29 19 28 20" src="https://github.com/user-attachments/assets/5cc6c97e-0b57-46e4-a85c-225baf3bb141">
<img width="598" alt="スクリーンショット 2024-08-29 19 27 41" src="https://github.com/user-attachments/assets/5db0e2b9-7f91-4e85-85bf-c875ff327174">

案件登録/編集画面 WF作成
[#124](https://github.com/RyosukeSakakibara718/project-balancer/issues/124)

案件登録画面/要件定義書作成
[#133](https://github.com/RyosukeSakakibara718/project-balancer/issues/133)

案件編集画面/要件定義書作成
[#134](https://github.com/RyosukeSakakibara718/project-balancer/issues/134)

## 山崎
検索機能 テスト作成
[#116](https://github.com/RyosukeSakakibara718/project-balancer/issues/116)

ページネーション テスト作成
[#117](https://github.com/RyosukeSakakibara718/project-balancer/issues/117)

メンバー詳細表示 エラーハンドリング作成
[#118](https://github.com/RyosukeSakakibara718/project-balancer/issues/118)

メンバー編集 エラーハンドリング作成
[#119](https://github.com/RyosukeSakakibara718/project-balancer/issues/119)

メンバー削除 エラーハンドリング作成
[#121](https://github.com/RyosukeSakakibara718/project-balancer/issues/121)

フロント/ルーティング設定
[#129](https://github.com/RyosukeSakakibara718/project-balancer/issues/129)

案件管理画面/フロント実装
[#130](https://github.com/RyosukeSakakibara718/project-balancer/issues/130)
   
## 奈良
エイリアスを設定して絶対パスでインポートするように修正
[#84](https://github.com/RyosukeSakakibara718/project-balancer/issues/84)

案件管理画面/バックエンド実装
[#123](https://github.com/RyosukeSakakibara718/project-balancer/issues/123)

API作成 検索機能
[#125](https://github.com/RyosukeSakakibara718/project-balancer/issues/125)

API作成 削除機能
[#126](https://github.com/RyosukeSakakibara718/project-balancer/issues/126)

# 方針
9月末までに完成を目指すためには
- テストを一旦放棄
- ドキュメントは作成をする
- デザイン・画面要件定義・フロント・バックエンドに分けて作成か？

**Comment by RyosukeSakakibara718** [comment]
OKです！！
ありがとうございます！

**Comment by yokohama-TN** [comment]
OKです！
ありがとうございます！
