### ISSUE TITLE
タスク管理やドキュメント管理の運用方法

### ISSUE THREAD

**Issue by RyosukeSakakibara718** [RyosukeSakakibara718/project-balancer_doc#5]
タスク管理に関して、下記Wikiに記載

https://github.com/RyosukeSakakibara718/project-balancer_doc/wiki/%E3%82%BF%E3%82%B9%E3%82%AF%E7%AE%A1%E7%90%86%E3%81%AB%E9%96%A2%E3%81%97%E3%81%A6#%E3%82%BF%E3%82%B9%E3%82%AF%E7%AE%A1%E7%90%86

ドキュメント管理に関して、下記Wikiに記載
https://github.com/RyosukeSakakibara718/project-balancer_doc/wiki/%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88%E7%AE%A1%E7%90%86%E3%81%AB%E9%96%A2%E3%81%97%E3%81%A6

作業の進め方に関して、下記Wikiに記載
https://github.com/RyosukeSakakibara718/project-balancer_doc/wiki/%E4%BD%9C%E6%A5%AD%E3%81%AE%E9%80%B2%E3%82%81%E6%96%B9

**Comment by RyosukeSakakibara718** [comment]
それぞれ確認してdoneにする

**Comment by tsukimi0618** [comment]
done
